#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

---
apiVersion: v1
kind: Secret
metadata:
  name: sso-credentials
  #! namespace: api-portal
  namespace: tap-install
type: Opaque
data:
  #@ if data.values.springApiPortalApiKeySupport:
  client-id: #@ base64.encode(data.values.oktaClientId)
  client-secret: #@ base64.encode(data.values.oktaClientSecret)
  issuer-uri:  #@ base64.encode(data.values.oktaIssuerUri)
  scope:  #@ base64.encode(data.values.oktaScopes)
  user-name-attribute:  #@ base64.encode(data.values.oktaUsernameAttribute)
  #@ end

