#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")


---
apiVersion: v1
kind: Secret
metadata:
  name: api-portal-sso-creds-import-secret
  namespace: tap-install
stringData:
  patch.yml: |
    ---
    apiVersion: secretgen.carvel.dev/v1alpha1
    kind: SecretImport
    metadata:
      name: sso-credentials
      namespace: api-portal
    spec:
      fromNamespace: tap-install