#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petclinic-gateway-cert
  namespace: default
spec:
  dnsNames:
  - petclinic.akslab.tap.fynesy.com
  #@ if data.values.tlsMode = 'tlsManual':
  secretName: tapfynesycom
  #@ else:
  secretName: petclinic-gateway-tls-cert
  #@ end
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer