#@ load("@ytt:data", "data")
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: app-resources
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
spec:
  serviceAccountName: sync-sa
  fetch:
    - git:
        ref: origin/akslab
        url: #@ data.values.tapGitopsInstallationRepositoryUrl
        subPath: clusters/taplab/cluster-config/app-resources
        secretRef:
          name: sync-git
  template:
    - ytt: {}
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
