apiVersion: v1
kind: Secret
metadata:
  name: ootb-supply-chain-overlay
  namespace: tap-install
type: Opaque
stringData:
  ootb-supply-chain-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:template", "template")
    #@ load("@ytt:data", "data")
    
    #@ def replace_value_to_default(left, right):
    #@   if "default" in left:
    #@     return left
    #@   end
    #@   param = dict(left)
    #@   param.update({"default": param.pop("value")})
    #@   return param
    #@ end
    
    #@ if data.values.external_delivery:
    #@overlay/match by=overlay.subset({"kind":"ClusterSupplyChain"}), expects="0+"
    ---
    spec:
      params:
      #@overlay/append
      - name: deliverable_server_address
        default: "https://github.com"
      - name: deliverable_repository_owner
        default: "tfynes-pivotal"
      - name: deliverable_repository_name
        default: "tapdemo1-deliverables"
      - name: deliverable_branch
        default: "main"

    #@overlay/match by=overlay.subset({"apiVersion": "carto.run/v1alpha1", "kind": "ClusterSupplyChain"}), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      #@overlay/remove
      - name: deliverable
    
    #@overlay/match by=overlay.subset({"kind":"ClusterSupplyChain"}), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      - name: config-writer
      #@overlay/append
      - name: deliverable-config
        templateRef:
          kind: ClusterConfigTemplate
          name: config-deliverable-template  
        params:
        - name: registry
          value: #@ data.values.registry
      - name: deliverable-config-writer
        configs:
        - name: config
          resource: deliverable-config
        params:
        - name: serviceAccount
          default: #@ data.values.service_account
        - name: registry
          value: #@ data.values.registry
        templateRef:
          kind: ClusterTemplate
          name: config-writer-deliverable-template

    #@ end