#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: full-deps-package-repo
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgr
spec:
  fetch:
    imgpkgBundle:
      #@ if data.values.platformRegistryLocation == 'customPlatformRegistrySelection':
      image: #@ data.values.customPlatformRegistryUrl + '/tbs-full-deps:1.8.0'
      #@ else:
      image: {}
      #@ end
      #!secretRef:
        #!name: install-registry-dockerconfig